"""change message

Revision ID: 177bd35f54d2
Revises: 193a806cdd31
Create Date: 2025-06-01 20:12:19.123043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177bd35f54d2'
down_revision: Union[str, None] = '193a806cdd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'body', new_column_name='text', type_=sa.String(length=500), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text', new_column_name='body', type_=sa.String(length=500), nullable=False)
    # ### end Alembic commands ###
