"""Next commit

Revision ID: 193a806cdd31
Revises: 63dc10c94b75
Create Date: 2025-05-22 22:00:41.725859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193a806cdd31'
down_revision: Union[str, None] = '63dc10c94b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    # op.drop_constraint('users_login_key', 'users', type_='unique')
    op.alter_column('users', 'login', new_column_name='username')
    # op.create_unique_constraint(None, 'users', ['username'])
    # op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
