"""empty message

Revision ID: 63dc10c94b75
Revises: 829e5aa12271
Create Date: 2025-05-16 21:41:59.810773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63dc10c94b75'
down_revision: Union[str, None] = '829e5aa12271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'))
    op.add_column('messages', sa.Column('room_id', sa.UUID(), nullable=False, comment='Room ID'))
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               comment='Message ID',
               existing_comment='Room ID',
               existing_nullable=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               comment='Room ID',
               existing_comment='Message ID',
               existing_nullable=False)
    op.drop_column('messages', 'room_id')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
