"""empty message

Revision ID: 8cc73783a985
Revises: 12eab96744a2
Create Date: 2025-04-10 21:34:57.223953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc73783a985'
down_revision: Union[str, None] = '12eab96744a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    # ### end Alembic commands ###
